// Test-only API responses. These fixtures are never imported by application code.
import type { FeedItem, ItemCard, Source } from '../api/types'
export const source: Source = { id: 1, name: 'Источник API', url: 'https://example.org/rss', fetch_url: 'https://example.org/rss', normalized_url: 'https://example.org/rss', kind: 'rss', category: 'media', status: 'active', poll_interval: '1h', next_run_at: null, category_hint: null, created_at: '2026-01-01T00:00:00Z', notes: '', deleted_at: null, created_by: '' }
export const item: FeedItem = { id: 101, title: 'Материал сервера', summary: 'Саммари сервера', type: 'news', priority: 'high', tags: ['регуляторика', 'тренды', 'API'], npa_status: null, npa_key: null, published_at: '2026-01-01T00:00:00Z', canonical_url: 'https://example.org/article', source_name: source.name, sources_count: 1, visibility: 'visible', hidden_reason: '', origin: 'collected', confidence: 0.8, relevance_score: 0.9, reasoning: 'Важен для компании', snippet: null, flags: { degraded: false, needs_review: false, edited: false, date_estimated: false } }
export const card: ItemCard = { item: { ...item, cluster_id: 10, analyst_note: '', manual_overrides: [], is_archived: false, degraded: false, needs_review: false, date_estimated: false, model_name: 'provider', prompt_version: 1, profile_version: 1, processed_at: '2026-01-01T00:00:00Z' }, canonical_url: item.canonical_url, sources: [{ id: 1, url: item.canonical_url!, title: item.title, source_name: source.name, published_at: item.published_at, is_canonical: 1 }], entities: [{ id: 1, role: 'impact', value: 'Новые требования', normalized_value: 'новые требования', evidence_start: null, evidence_end: null }], events: [], revisions: [], notes: [], tags: item.tags.map(tag => ({ item_id: item.id, tag, is_manual: false })), model_proposals: { title: null, summary: null } }
export const filters = { sources: [source], priorities: ['high', 'medium', 'low'], types: ['news', 'npa'], tags: ['API'], npa_statuses: ['анонс', 'рассмотрение', 'действует', 'архив'], orders: ['published', 'priority', 'processed'], timezone: 'Europe/Moscow' }
export const status = { last_collect_at: null, documents: 1, items: 1, unprocessed: 0, sources: { active: 1 }, stale_sources: [], timezone: 'Europe/Moscow' }
export const health = { status: 'ok', app: 'hub', environment: 'local', version: '1', checks: { repository: 'ok' } }

export const processingRun = { id: 7, started_at: '2026-01-01T00:00:00Z', finished_at: null, status: 'running', trigger: 'api', params: {}, documents: 0, clusters: 0, items_new: 0, items_joined: 0, items_updated: 0, degraded: 0, needs_review: 0, calls: 0, failed: 0, elapsed_s: 0, error: '' }
export const processing = { running: null, last: null, unprocessed: 1, llm_available: false }
export const collection = { running: false, busy: false, interval_seconds: 900, started_at: null, next_tick_at: null, cycles: 0, last_error: '', due_sources: 1, last_collect: null }
